name: Build Sailing Stats Raspberry Pi image

on:
  push:
    branches:
    - master

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: sailingstats
          hostname: sailingstats
          enable-ssh: 1
          stage-list: stage0 stage1 stage2
          disable-first-boot-user-rename: 1
          username: sailingstats
          password: R9#4Bg
          verbose-output: true
          pi-gen-repository: sailingstats/pi-gen

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}